node_id: "opencanary-1"
hostname: "SRV01"
portscan_enabled: "false"
smb_enabled: "false"
ssh_enabled: "true"
ssh_version: "SSH-2.0-OpenSSH_5.1p1 Debian-4"
rdp_enabled: "false"
mysql_enabled: "false"
mysql_banner: "5.5.43-0ubuntu0.14.04.1"
mssql_enabled: "false"
mssql_version: "2012" # Either 2008R2, 2012 or 2014
ntp_enabled: "false"
snmp_enabled: "false"
http_enabled: "true"
http_banner: "Apache/2.2.22 (Ubuntu)"
ftp_enabled: "true"
ftp_banner: "FTP server ready"
git_enabled: "false"
redis_enabled: "false"
sip_enabled: "false"
tftp_enabled: "false"
telnet_enabled: "false"
vnc_enabled: "false"
httpproxy_enabled: "false"